# Generated by Django 4.1.2 on 2022-10-14 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosno', '0002_alter_set_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='date',
        ),
        migrations.AddField(
            model_name='set',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
