# Generated by Django 4.1.2 on 2022-10-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosno', '0003_remove_set_date_set_created_set_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
