# Generated by Django 4.1.2 on 2022-10-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosno', '0004_alter_set_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninexam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prosno.question', unique=True),
        ),
        migrations.AlterField(
            model_name='questioninexam',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prosno.set', unique=True),
        ),
    ]
