# Generated by Django 4.1.2 on 2022-10-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosno', '0005_alter_questioninexam_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninexam',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prosno.question'),
        ),
        migrations.AlterField(
            model_name='questioninexam',
            name='set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prosno.set'),
        ),
    ]
